GET http://localhost:3001/api/blogs HTTP/1.1
content-type: application/json

{}

###

POST http://localhost:3001/api/blogs HTTP/1.1
content-type: application/json

{
"author": "Test Author",
"title": "Test Title",
"url": "testurl.com"
}