GET http://localhost:3001/api/blogs HTTP/1.1
content-type: application/json

###

GET http://localhost:3001/api/blogs?search=test HTTP/1.1
content-type: application/json

###

POST http://localhost:3001/api/blogs HTTP/1.1
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RAdXNlcm5hbWUuY29tIiwiaWQiOjEsImlhdCI6MTcxMTAyNDI5Nn0.JxSHWW4jgu8pWGPKGDUlhYIiPzmaOYaku_wXiWSAT30

{
  "author": "Test Author",
  "title": "test Title",
  "url": "test.com/url"
}

###

DELETE http://localhost:3001/api/blogs/7 HTTP/1.1
content-type: application/json

###

DELETE http://localhost:3001/api/blogs/7 HTTP/1.1
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RAdXNlcm5hbWUuY29tIiwiaWQiOjEsImlhdCI6MTcxMTAyNTIxNn0.I-AxtxbT1DCmCTn1No9WMoETKX4P8jYU2ZHJfLd2cIk

###

PUT http://localhost:3001/api/blogs/5 HTTP/1.1
content-type: application/json
